console.log(5 >= 1);                    // true
console.log(0 === 1);                   // false
console.log(4 <= 1);                    // false
console.log(1 != 1);                    // false
console.log(1 == "1");                  // true
console.log(1 === "1");                 // false
console.log("2" == "2");                // true
console.log("2" === "2");               // true
console.log("12" !== 12);               // true
console.log("15" != 15);                // false
console.log("A" > "B");                 // false
console.log("B" < "C");                 // true
console.log("a" > "A");                 // true
console.log("b" < "A");                 // false
console.log("bee" > "bbe");             // true
console.log("BeE" < "Bee");             // true
console.log("SonTer" > "Soncom");       // false
console.log("circle" > "circles");      // false
console.log("NaRuTo" < "nArUtO");       // true
console.log(true === false);            // false
console.log(true != true);              // false